version: '3'

services:
  fantasydb:
    image: mariadb:10.3
    container_name: fc-mariadb
    volumes:
      - fantasy-calendar-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fantasy-calendar
    ports:
      - "13306:3306"

  fpm:
    container_name: fantasy_calendar_php
    image: fc-php
    build:
      context: https://github.com/fantasycalendar/Fantasy-Calendar.git
      dockerfile: Dockerfile
    ports:
      - "9980:8080" # Change to your own port of course

  queue-worker:
    container_name: fantasy_calendar_php
    depends_on:
      - fpm
    image: fc-php
    build:
      context: https://github.com/fantasycalendar/Fantasy-Calendar.git
      dockerfile: Dockerfile
    command: ["/usr/bin/php", "/var/task/artisan", "queue:work"]

  fcredis:
    image: redis
    container_name: fcredis
    depends_on:
      - fantasy-calendar-php

volumes:
  fantasy-calendar-db:
