<?php

namespace Tests\Feature;

use App\Services\RendererService\ImageRenderer;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Imagick;
use Tests\TestCase;

class ImageRendererTest extends TestCase
{
    public function setUp(): void
    {
        Storage::disk('local')->makeDirectory('tmp');

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown(): void
    {
        Storage::disk('local')->deleteDirectory('tmp');

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testImageRenderer()
    {
        $this->getEdgeCases()->each(function($calendar){
            collect($calendar->static_data['imagerenderer_testcases'])->each(function($testCase) use ($calendar) {
                $expectationBlob = Storage::disk('base')->get($testCase['expectation_filename']);
                $freshBlob = ImageRenderer::renderMonth($calendar, collect([
                    'ext' => 'png',
                    'year' => $testCase['year'] ?? 0,
                    'month_id' => $testCase['month'] ?? 0,
                    'day' => $testCase['day'] ?? 1,
                ]))->encode();

//                Storage::disk('local')->put('tmp/' . Str::slug(Str::ascii($calendar->name)) . '_' . Str::slug(Str::ascii($calendar->current_date)) . '.png', $freshBlob);

                $this->assertEquals(0.0, $this->compareImages($expectationBlob, $freshBlob));
            });
        });
    }

    private function compareImages($blob1, $blob2)
    {
        $image1 = new Imagick();
        $image1->readImageBlob($blob1);
        $image2 = new Imagick();
        $image2->readImageBlob($blob2);

        $result = $image1->compareImages($image2, Imagick::METRIC_MEANSQUAREERROR);
        $result[0]->setImageFormat("png");

        return $result[1];
    }
}
