on:
  workflow_dispatch:

jobs:
  website-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@main
        with:
          node-version: '14'
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Run composer
        uses: nick-zh/composer-php@master
        with:
          action: 'install -oa --ignore-platform-reqs --no-dev'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create env file
        run: |
          cat > .env << EOF
          APP_ENV=production
          APP_URL=https://fantasy-calendar-website.s3.amazonaws.com/
          EOF
      - name: Install NPM dependencies
        run: npm install
      - name: Build production assets
        run: npm run production
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Export pages to HTML
        env:
          APP_URL: https://fantasy-calendar-website.s3.amazonaws.com/
        run: php artisan export
      - name: Copy assets into S3
        run: |
          aws s3 sync ./dist s3://fantasy-calendar-website/
